description: VLT5 pretrain

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-wjin
    mount_dir: /mnt/root

environment:
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
  # image: mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04
  # image: mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
  registry: docker.io # any public registry can be specified here
  setup:
    - pip install -r requirements.txt
  image_setup:
    - apt-get update -y
    - apt-get -y install openssh-client vim tmux sudo apt-transport-https apt-utils curl git wget lsb-release ca-certificates gnupg gcc g++ pv iftop openmpi-bin openmpi-common libopenmpi-dev
    

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  # local_dir: $CONFIG_DIR/src
  local_dir: $CONFIG_DIR

# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example

# sku:
#     - Field SKU ('G9') should be one of ['G0', 'G1', 'G2', 'G4', 'G8', 'G16', '16G1',
#       '16G4', '16G8', '24G1', '24G2', '24G4', '24G8', '32G4', '32G8', '32G16', '64G4',
#       '40G8']

jobs:


# - name: train_feat
#   sku : G1
#   command:
#   - python tsv_to_h5.py

# - name: train_feat2
#   sku : G1
#   command:
#   - python tsv_to_h5.py

# - name: train_feat3
#   sku : G1
#   command:
#   - python tsv_to_h5.py

# - name: train_feat_attr
#   sku : G1
#   command:
#   - python tsv_to_h5_attrw.py

- name: make_meta2
  sku : G1
  command:
  - python make_dict.py






# - name: id0
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 0

# - name: id1
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 1

# - name: id2
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 2

# - name: id3
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 3

# - name: id4
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 4

# - name: id5
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 5
# - name: id6
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 6

# - name: id7
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 7

# - name: id8
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 8
# - name: id9
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 9
# - name: id10
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 10

# - name: id11
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 11
# - name: id12
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 12

# - name: id13
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 13

# - name: id14
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 14
# - name: id15
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 15
# - name: id16
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 16

# - name: id17
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 17
# - name: id18
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 18

# - name: id19
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 19

# - name: id20
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 20
# - name: id21
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 21

# - name: id22
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 22

# - name: id23
#   sku : G1
#   command:
#   - python tsv_to_h5_attr.py --id 23









# - name: ids0
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 0

# - name: ids1
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 1

# - name: ids2
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 2

# - name: ids3
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 3

# - name: ids4
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 4

# - name: ids5
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 5
# - name: ids6
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 6

# - name: ids7
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 7

# - name: ids8
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 8
# - name: ids9
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 9
# - name: ids10
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 10

# - name: ids11
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 11
# - name: ids12
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 12

# - name: ids13
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 13

# - name: ids14
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 14
# - name: ids15
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 15
# - name: ids16
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 16

# - name: ids17
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 17
# - name: ids18
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 18

# - name: ids19
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 19

# - name: ids20
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 20
# - name: ids21
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 21

# - name: ids22
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 22

# - name: ids23
#   sku : G1
#   command:
#   - python tsv_to_h5.py --id 23


