description: VLT5 pretrain

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-wjin
    mount_dir: /mnt/root

environment:
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
  # image: mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04
  registry: docker.io # any public registry can be specified here
  setup:
    # - sudo pip install -U pip setuptools
    # - sudo apt-get install git
    # - pip install --upgrade pip
    - pip install git+https://github.com/j-min/language-evaluation.git
    - pip install -r requirements.txt
    - python -m spacy download en_core_web_sm

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  # local_dir: $CONFIG_DIR/src
  local_dir: $CONFIG_DIR

# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example

# sku:
#     - Field SKU ('G9') should be one of ['G0', 'G1', 'G2', 'G4', 'G8', 'G16', '16G1',
#       '16G4', '16G8', '24G1', '24G2', '24G4', '24G8', '32G4', '32G8', '32G16', '64G4',
#       '40G8']

jobs:
- name: prefix
  sku: G4
  command:
  - bash scripts/pretrain_VLT5_prefix.sh 4

- name: prefix_only
  sku: G8
  command:
  - bash scripts/pretrain_VLT5_prefixonly.sh 8

- name: ar
  sku: G8
  command:
  - bash scripts/pretrain_VLT5_ar.sh 8


- name: prefix_no_desc
  sku: G8
  command:
  - bash scripts/pretrain_VLT5_prefix.sh 8 --output /mnt/root/vlt5/pretrain/prefix_no_desc

- name: lm_noun
  sku: G8
  command:
  - bash scripts/pretrain_VLT5_lmnoun.sh 8 --output /mnt/root/vlt5/pretrain/lmnoun


